# mybatis 관련 설정
mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: mapper/*.xml
  # alias 설정
  # Spring Framework처럼 이름을 사용하기 편하게 바꿔주는게 아니라 길이를 줄여주는 역할.
  # IntelluJ는 자동완성을 지원하기 때문에 굳이 안써도 됨.
  # type-aliases-package: com.icia.member.dto